version: "3.8"

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    networks:
      - app-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    depends_on:
      - client
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
